### ISSUE TITLE
list_new plugin doesn't work with 2.1.7

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2854]
After installing list_new plugin, administration doesn't work.

Console:
 
![image](https://user-images.githubusercontent.com/5429548/32550411-54693004-c48d-11e7-8ab8-70ae2fa24cab.png)

**Comment by tgtje** [comment]
just addin (php 7.1 x )  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead, Line 539 And indeed you message..BUT there is **NO e107_files** in v2 (only legacy)

(FF mine : TypeError: "Are you sure?".addModLan is not a function[Meer info]  admin_list_config.php:63:5
Laden voor het <script> met bron ‘http://localhost/e107/e107_files/jslib/core/admin.js’ is mislukt.)

**Comment by Jimmi08** [comment]
I got admin part working. I don't know how to fix this: (all parts has e-hideme class)

![image](https://user-images.githubusercontent.com/5429548/32952511-d28ac37c-cbad-11e7-9ead-b80da56edea7.png)

it's loaded this way:
```
function admin_list_config_adminmenu()
{
	$act = "";
	unset($var);
	$var=array();
	//$var['general']['text'] = LIST_ADMIN_OPT_1;
	$var['list-new-recent-page']['text'] = LIST_ADMIN_OPT_2;
	$var['list-new-recent-menu']['text'] = LIST_ADMIN_OPT_3;
	$var['list-new-new-page']['text'] = LIST_ADMIN_OPT_4;
	$var['list-new-new-menu']['text'] = LIST_ADMIN_OPT_5;
	e107::getNav()->admin(LAN_OPTIONS.'--id--list_new', 'list-new-recent-page', $var);

```

You need to click on other tab and go back to first one, otherwise there is nothing displayed
![image](https://user-images.githubusercontent.com/5429548/32952614-15c37f9e-cbae-11e7-8dbf-1d0b8576913d.png)

**Comment by Jimmi08** [comment]
About frontend  -  I can't get it fully work because this onclick='expandit(this);' doesn't work
